# Generated by Django 2.0.1 on 2018-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userpic',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
