# Generated by Django 2.0.1 on 2018-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20180107_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='type',
            field=models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('GitHub', 'GitHub'), ('Upwork', 'Upwork')], max_length=255),
        ),
    ]
