# Generated by Django 2.0.1 on 2018-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Angular', 'Angular'), ('jQuery', 'jQuery'), ('Bootstrap', 'Bootstrap'), ('Gulp', 'Gulp'), ('Heroku', 'Heroku'), ('Docker', 'Docker'), ('Linux', 'Linux'), ('Git', 'Git')], max_length=255),
        ),
    ]
